import debounce from 'lodash-es/debounce';
import find from 'lodash-es/find';
import { assertIsDefined } from './base';
import type { RepoList } from './options/model';

type ConfigRule = {
  regex: RegExp;
  hide: boolean;
};

type Config = {
  repo: string;
  rules: readonly ConfigRule[];
  autogenerated: boolean;
};

let configs: readonly Config[] = [];

// Track files we've already processed so we don't re-process or miss new ones
const processedFiles = new Set<string>();

let oldHref = document.location.href;
const observer = new MutationObserver(() => {
  if (oldHref != document.location.href) {
    oldHref = document.location.href;
    processedFiles.clear();
    if (shouldActivate()) {
      markAllAsViewed();
    }
  } else if (shouldActivate()) {
    markAllAsViewed();
  }
});
const bodyEl = document.querySelector('body');
assertIsDefined(bodyEl, '"body" elements must exist');
observer.observe(bodyEl, {
  childList: true,
  subtree: true,
});

function findRepoConfig(): Config | undefined {
  const pathname = window.location.pathname.toLowerCase();
  return find(configs, (config) => pathname.startsWith(`/${config.repo}/`));
}

function shouldActivate(): boolean {
  const pathname = window.location.pathname;
  return (
    (pathname.endsWith('/files') || pathname.endsWith('/changes')) &&
    !!findRepoConfig()
  );
}

type FileEntry = {
  filename: string;
  viewedButton: HTMLButtonElement | null;
  headerElement: Element;
};

function getFileEntries(): FileEntry[] {
  const entries: FileEntry[] = [];
  const seen = new Set<string>();

  const viewedButtons = document.querySelectorAll(
    'button[aria-label="Viewed"], button[aria-label="Not Viewed"]',
  );
  for (const btn of viewedButtons) {
    const viewedButton = btn as HTMLButtonElement;

    let header: Element | null = btn.parentElement;
    let filename: string | null = null;
    while (header && header !== document.body) {
      const expandBtn = header.querySelector('button[data-file-path]');
      if (expandBtn) {
        filename = expandBtn.getAttribute('data-file-path');
        break;
      }
      const codeEl = header.querySelector('h3 a code');
      if (codeEl) {
        filename = (codeEl.textContent || '')
          .replace(/[\u200E\u200F\u200B\u2069\u2066]/g, '')
          .trim();
        break;
      }
      header = header.parentElement;
    }

    if (!filename || !header || header === document.body) continue;
    if (seen.has(filename)) continue;

    seen.add(filename);
    entries.push({ filename, viewedButton, headerElement: header });
  }

  return entries;
}

const markAllAsViewed = debounce(() => {
  const config = findRepoConfig();
  assertIsDefined(config, '"config" should exist');

  const entries = getFileEntries();
  const newEntries = entries.filter((e) => !processedFiles.has(e.filename));
  if (newEntries.length === 0) return;

  const toHide: FileEntry[] = [];

  for (const entry of newEntries) {
    processedFiles.add(entry.filename);
    try {
      let handled = false;
      config.rules.forEach((rule) => {
        if (rule.regex.test(entry.filename)) {
          handled = true;
          markAsViewed(entry);
          if (rule.hide) {
            toHide.push(entry);
          }
        }
      });

      if (config.autogenerated && !handled) {
        const generatedFile = !!entry.headerElement.textContent?.match(
          'Some generated files are not rendered by default',
        );
        if (generatedFile) {
          markAsViewed(entry);
        }
      }
    } catch (error) {
      // Skip files we can't process
    }
  }

  if (toHide.length > 0) {
    setTimeout(() => {
      for (const entry of toHide) {
        hideFile(entry);
      }
    }, 500);
  }
}, 200);

function markAsViewed(entry: FileEntry) {
  if (!entry.viewedButton) return;

  const isViewed = entry.viewedButton.getAttribute('aria-pressed') === 'true';
  const checkbox = entry.viewedButton.parentElement?.querySelector(
    'input[name="viewed"]',
  ) as HTMLInputElement | null;
  const alreadyViewed = isViewed || (checkbox?.checked ?? false);

  if (!alreadyViewed) {
    entry.viewedButton.click();
  }
}

function hideFile(entry: FileEntry) {
  let container: Element = entry.headerElement;
  const maxDepth = 10;
  let depth = 0;

  while (
    container.parentElement &&
    container.parentElement !== document.body &&
    depth < maxDepth
  ) {
    if (container.querySelector('table[data-diff-anchor]')) break;
    if (container.getAttribute('data-file-path')) break;
    if (container.classList.contains('file')) break;
    if (container.tagName.toLowerCase().includes('diff')) break;

    container = container.parentElement;
    depth++;
  }

  // If we hit the safety limit, don't hide — we'd blank the page
  if (depth >= maxDepth) return;

  (container as HTMLElement).style.display = 'none';
}

chrome.storage.sync.get(['db'], (result) => {
  const repoList: RepoList =
    'db' in result ? (result.db as RepoList) : { repos: [] };
  configs = repoList.repos.map((repo) => ({
    repo: repo.name,
    rules: repo.rules.map((rule) => ({
      regex: new RegExp(rule.regex),
      hide: rule.hide,
    })),
    autogenerated: !!repo.autogenerated,
  }));
  if (shouldActivate()) {
    markAllAsViewed();
  }
});
