import debounce from 'lodash-es/debounce';
import find from 'lodash-es/find';
import { assertIsDefined } from './base';
import type { RepoList } from './options/model';

const LOG_PREFIX = '[autoviewed]';

type ConfigRule = {
  regex: RegExp;
  hide: boolean;
};

type Config = {
  repo: string;
  rules: readonly ConfigRule[];
  autogenerated: boolean;
};

let configs: readonly Config[] = [];

// Track files we've already processed so we don't re-process or miss new ones
const processedFiles = new Set<string>();

console.log(LOG_PREFIX, 'Content script loaded on:', document.location.href);

let oldHref = document.location.href;
const observer = new MutationObserver(() => {
  if (oldHref != document.location.href) {
    oldHref = document.location.href;
    processedFiles.clear();
    if (shouldActivate()) {
      markAllAsViewed();
    }
  } else if (shouldActivate()) {
    markAllAsViewed();
  }
});
const bodyEl = document.querySelector('body');
assertIsDefined(bodyEl, '"body" elements must exist');
observer.observe(bodyEl, {
  childList: true,
  subtree: true,
});

function findRepoConfig(): Config | undefined {
  const pathname = window.location.pathname.toLowerCase();
  return find(configs, (config) => pathname.startsWith(`/${config.repo}/`));
}

function shouldActivate(): boolean {
  const pathname = window.location.pathname;
  return (
    (pathname.endsWith('/files') || pathname.endsWith('/changes')) &&
    !!findRepoConfig()
  );
}

type FileEntry = {
  filename: string;
  viewedButton: HTMLButtonElement | null;
  headerElement: Element;
};

/**
 * Get all file entries from the page.
 * New GitHub DOM: file headers contain both filename and Viewed button.
 * Old GitHub DOM: <div class="file"> with form-based checkbox.
 */
function getFileEntries(): FileEntry[] {
  const entries: FileEntry[] = [];
  const seen = new Set<string>();

  // Find all Viewed/Not Viewed buttons — the one consistent element across GitHub's DOM variants
  const viewedButtons = document.querySelectorAll(
    'button[aria-label="Viewed"], button[aria-label="Not Viewed"]',
  );
  for (const btn of viewedButtons) {
    const viewedButton = btn as HTMLButtonElement;

    // Walk up to find the file header container
    let header: Element | null = btn.parentElement;
    let filename: string | null = null;
    while (header && header !== document.body) {
      // Try data-file-path on an expand button
      const expandBtn = header.querySelector('button[data-file-path]');
      if (expandBtn) {
        filename = expandBtn.getAttribute('data-file-path');
        break;
      }
      // Try h3 > a > code (diff-file-header pattern)
      const codeEl = header.querySelector('h3 a code');
      if (codeEl) {
        filename = (codeEl.textContent || '')
          .replace(/[\u200E\u200F\u200B\u2069\u2066]/g, '')
          .trim();
        break;
      }
      header = header.parentElement;
    }

    if (!filename || !header || header === document.body) continue;
    if (seen.has(filename)) continue;

    seen.add(filename);
    entries.push({ filename, viewedButton, headerElement: header });
  }

  console.log(LOG_PREFIX, 'Found', entries.length, 'file entries');
  return entries;
}

const markAllAsViewed = debounce(() => {
  const config = findRepoConfig();
  assertIsDefined(config, '"config" should exist');

  const entries = getFileEntries();
  // Only process new files we haven't seen yet
  const newEntries = entries.filter((e) => !processedFiles.has(e.filename));
  if (newEntries.length === 0) return;

  console.log(
    LOG_PREFIX,
    'Processing',
    newEntries.length,
    'new files (',
    entries.length,
    'total)',
  );

  const toHide: FileEntry[] = [];

  for (const entry of newEntries) {
    processedFiles.add(entry.filename);
    try {
      let handled = false;
      config.rules.forEach((rule) => {
        const matches = rule.regex.test(entry.filename);
        if (matches) {
          console.log(
            LOG_PREFIX,
            'Rule matched:',
            entry.filename,
            '| pattern:',
            rule.regex.source,
            '| hide:',
            rule.hide,
          );
          handled = true;
          markAsViewed(entry);
          if (rule.hide) {
            toHide.push(entry);
          }
        }
      });

      if (!handled) {
        console.log(LOG_PREFIX, 'No rule matched:', entry.filename);
      }

      if (config.autogenerated && !handled) {
        const generatedFile = !!entry.headerElement.textContent?.match(
          'Some generated files are not rendered by default',
        );
        if (generatedFile) {
          console.log(
            LOG_PREFIX,
            'Auto-generated file detected:',
            entry.filename,
          );
          markAsViewed(entry);
        }
      }
    } catch (error) {
      console.error(LOG_PREFIX, 'Error processing:', entry.filename, error);
    }
  }

  // Hide files after a delay so the Viewed click has time to register with React
  if (toHide.length > 0) {
    setTimeout(() => {
      for (const entry of toHide) {
        hideFile(entry);
      }
    }, 500);
  }
}, 200);

function markAsViewed(entry: FileEntry) {
  if (!entry.viewedButton) {
    console.error(LOG_PREFIX, 'No Viewed button for:', entry.filename);
    return;
  }

  const ariaPressed = entry.viewedButton.getAttribute('aria-pressed');
  const ariaLabel = entry.viewedButton.getAttribute('aria-label');
  const isViewed = ariaPressed === 'true';
  // Old DOM: check if it's a label wrapping a checkbox
  const checkbox = entry.viewedButton.parentElement?.querySelector(
    'input[name="viewed"]',
  ) as HTMLInputElement | null;
  const alreadyViewed = isViewed || (checkbox?.checked ?? false);

  console.log(
    LOG_PREFIX,
    'markAsViewed:',
    entry.filename,
    '| aria-pressed:',
    ariaPressed,
    '| aria-label:',
    ariaLabel,
    '| alreadyViewed:',
    alreadyViewed,
  );

  if (!alreadyViewed) {
    console.log(LOG_PREFIX, 'Clicking Viewed for:', entry.filename);
    entry.viewedButton.click();
  } else {
    console.log(LOG_PREFIX, 'Already viewed, skipping:', entry.filename);
  }
}

/**
 * GitHub lazy-loads file diffs as you scroll. This function scrolls down the
 * page incrementally to force all files to load, clicks any "Load diff" buttons,
 * then scrolls back to the original position.
 */
function hideFile(entry: FileEntry) {
  // Hide the entire file section
  let container = entry.headerElement;
  // Walk up to find the file's outermost container that includes the diff table
  while (container.parentElement && container.parentElement !== document.body) {
    const table = container.querySelector('table[data-diff-anchor]');
    if (table) break;
    container = container.parentElement;
  }
  (container as HTMLElement).style.display = 'none';
}

chrome.storage.sync.get(['db'], (result) => {
  console.log(LOG_PREFIX, 'Storage loaded:', JSON.stringify(result));
  const repoList: RepoList =
    'db' in result ? (result.db as RepoList) : { repos: [] };
  configs = repoList.repos.map((repo) => ({
    repo: repo.name,
    rules: repo.rules.map((rule) => ({
      regex: new RegExp(rule.regex),
      hide: rule.hide,
    })),
    autogenerated: !!repo.autogenerated,
  }));
  console.log(
    LOG_PREFIX,
    'Configs loaded:',
    configs.map((c) => ({ repo: c.repo, rules: c.rules.length })),
  );
  if (shouldActivate()) {
    markAllAsViewed();
  }
});
